### ISSUE TITLE
Demo: CubeCarving: The cube cannot be carved in Unity

### ISSUE THREAD

**Issue by MingSongJiang** [InfinyTech3D/SofaUnity#112]
Hello!
The cube cannot be cut apart in Unity. .Is there something I need to set up？
Sofa:V23.12
Unity:2023.3.41
Scene:Demo_03_CubeCarving  Demo_04_CubeAdvancedCarving

![1](https://github.com/user-attachments/assets/a24316f8-bf8f-4710-93df-1ec718980524)

**Comment by MingSongJiang** [comment]
Press space keyboard to active the feature.

**Comment by epernod** [comment]
thank you for the feedback.
You can find all instruction on this page: https://infinytech3d.com/examples-interactions/
We will make sure to improve it to make it clearer.

**Comment by MingSongJiang** [comment]
Hello,
If I want to cut my own rigid body model in Unity3d, how do I do it?
In the demo, the cut at the carving is rough, and the cut is not closed.And no matter where I put the cube, the ball cuts in the same place.
Sofa:V23.12
Unity:2020.3.32




Best regards.




蒋明松


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InfinyTech3D/SofaUnity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月23日(星期五) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InfinyTech3D/SofaUnity] Demo: CubeCarving: The cube cannot be carved in Unity (Issue #112)





 
thank you for the feedback.
 You can find all instruction on this page: https://infinytech3d.com/examples-interactions/
 We will make sure to improve it to make it clearer.

**Comment by epernod** [comment]
hello could you open a github discussion [here](https://github.com/InfinyTech3D/SofaUnity/discussions/categories/help-using-the-software) instead. this is not really an issue. 
Thank you

**Comment by MingSongJiang** [comment]
Hello,
I am sorry,but I asked my question in discord and github discussion,nobody answer,so I'm sending this email to see if anyone can answer this question.
Thank you!



蒋明松


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InfinyTech3D/SofaUnity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月26日(星期一) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InfinyTech3D/SofaUnity] Demo: CubeCarving: The cube cannot be carved in Unity (Issue #112)





 
hello could you open a github discussion here instead. this is not really an issue.
 Thank you

**Comment by epernod** [comment]
Hi,

We are answering Github discussions as soon as we can. Remember that we are
doing this for free. If you would like faster and dedicated support, please
consider sponsoring us <https://github.com/sponsors/InfinyTech3D> or buying
a SDK with support <https://infinytech3d.com/licenses/>.

Best regards


Le mar. 27 août 2024 à 05:20, MingSongJiang ***@***.***> a
écrit :
