### ISSUE TITLE
If I want to cut my own rigid body model in Unity3d,  how do I do it?

### ISSUE THREAD

**Issue by MingSongJiang** [InfinyTech3D/SofaUnity#113]
Hello,
If I want to cut my own rigid body model in Unity3d,  how do I do it?
In the demo, the cut at the carving is rough, and the cut is not closed.And no matter where I put the cube, the ball cuts in the same place.
Sofa:V23.12
Unity:2020.3.32
![2](https://github.com/user-attachments/assets/02581888-a773-4849-8089-6ee5d04310f0)
![3](https://github.com/user-attachments/assets/108416f7-ebae-43d2-946d-8f2bae03a2e1)

**Comment by epernod** [comment]
This is not an issue but a discussion. Check https://github.com/InfinyTech3D/SofaUnity/discussions/114
